### ISSUE TITLE
Should we initialize the DB once per test case or once per step?

### ISSUE THREAD

**Issue by nalepae** [eth-clients/slashing-protection-interchange-tests#16] opened 2023-11-27 14:58 UTC
Tests specify:

> To run a test, first initialize a new (empty) slashing protection database.
Then for each entry in steps, import the interchange, process the blocks and attestations, and continue to the next step.

(A test can contain one to multiple steps)

My understanding reading these 2 sentences are:
- At test start, initialize and (empty) DB
- Then, on each `step`, import the `interchange`, process the `blocks`...

And so, do **not** re-initialize the DB at each step.

However, it seems tests themselves contradict each other:
1. In test [Multiple Interchanges Single Validator Single Message Gap](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/v5.2.1/tests/generated/multiple_interchanges_single_validator_single_message_gap.json):
    - In step 1, [we import a DB with a minimal block signed at slot 40](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/v5.2.1/tests/generated/multiple_interchanges_single_validator_single_message_gap.json#L17-L19) and [no block is signed at runtime](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/v5.2.1/tests/generated/multiple_interchanges_single_validator_single_message_gap.json#L30).
    - In step 2, [we import a DB with a minimal block signed at slot 50](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/v5.2.1/tests/generated/multiple_interchanges_single_validator_single_message_gap.json#L45-L47), then [we attempt to sign 3 blocks at slots 41, 45 and 49](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/v5.2.1/tests/generated/multiple_interchanges_single_validator_single_message_gap.json#L59-L76). These signatures should fail. Slots 41, 45 and 49 should theoretically **not** fail if we initialize the DB once per test case because the lowest signed slot in the DB is at slot 40 (imported in step 1) and there is not equivocating blocks at these slots. ==> **I understand here that we should initialise 1 DB per step, and not 1 DB per test.**

2. In test Multiple [Interchanges Overlapping Validators Merge Stale](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/master/tests/generated/multiple_interchanges_overlapping_validators_merge_stale.json):
    - In step 1, [we import a DB with a block signed at slot 100 (with no signing root)](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/master/tests/generated/multiple_interchanges_overlapping_validators_merge_stale.json#L17-L19)  and [the minimal imported block is at slot 4](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/master/tests/generated/multiple_interchanges_overlapping_validators_merge_stale.json#L45-L47), and [no block is signed at runtime](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/master/tests/generated/multiple_interchanges_overlapping_validators_merge_stale.json#L58).
    - In step 2, [we import a DB with a minimal block signed at slot 2](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/master/tests/generated/multiple_interchanges_overlapping_validators_merge_stale.json#L73-L75), and we do not import a block at slot 100. However, [we try to sign a block at slot 100 that should fail](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/master/tests/generated/multiple_interchanges_overlapping_validators_merge_stale.json#L115-L120) (because the block at slot 100 already in the DB has no signing root saved, so we consider it at slashable). ==> **I understand here that we should initialise 1 DB per test, and not 1 DB per step.**

----------

- My conclusion of `1.` is I understand that **we should initialise 1 DB per step, and not 1 DB per test.**
- My conclustion of `2.` is I understand that **we should initialise 1 DB per test, and not 1 DB per step.**

Or maybe [Multiple Interchanges Single Validator Single Message Gap](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/v5.2.1/tests/generated/multiple_interchanges_single_validator_single_message_gap.json) has an issue and [these signatures](https://github.com/eth-clients/slashing-protection-interchange-tests/blob/v5.2.1/tests/generated/multiple_interchanges_single_validator_single_message_gap.json#L59-L76) should be allowed?

**Comment by michaelsproul** [comment] 2023-11-27 22:59
One import per test case (_not_ per step) is what was intended. I think the issue in #17 is separate. If we resolve that, then I'll close this issue.

**Comment by michaelsproul** [comment] 2023-11-28 11:21
Ah right, I didn't spot that you were talking about a different test case. I think the fundamental issue is the same as #17: Complete vs Minimal. I'll try to amend this test case per your suggestions when I edit #17

Thanks!

**Closed** 2023-12-04 05:39 UTC
